In [1]:
import pandas as pd

In [7]:
data = [
    {
        "student_id": 101,
        "name": "Amir Shaikh",
        "age": 22,
        "gender": "Male",
        "email": "amir.shaikh@gmail.com",
        "status": "Active"
    },
    {
        "student_id": 102,
        "name": "Rahul Patil",
        "age": 21,
        "gender": "Male",
        "email": "rahul.patil@gmail.com",
        "status": "Active"
    },
    {
        "student_id": 103,
        "name": "Sneha Jadhav",
        "age": 20,
        "gender": "Female",
        "email": "sneha.jadhav@gmail.com",
        "status": "Inactive"
    },
    {
        "student_id": 104,
        "name": "Priya Sharma",
        "age": 22,
        "gender": "Female",
        "email": "priya.sharma@gmail.com",
        "status": "Active"
    },
    {
        "student_id": 105,
        "name": "Amit Kumar",
        "age": 23,
        "gender": "Male",
        "status": "Active"
    },
    {
        "student_id": 106,
        "name": "Pooja Singh",
        "age": 21,
        "gender": "Female",
        "status": "Active"
    },
    {
        "student_id": 107,
        "name": "Rohan Deshmukh",
        "age": 22,
        "gender": "Male",
        "email": "rohan.deshmukh@gmail.com",
        "status": "Inactive"
    },
    {
        "student_id": 108,
        "name": "Neha Verma",
        "age": 20,
        "gender": "Female",
        "email": "neha.verma@gmail.com",
        "status": "Active"
    },
    {
        "student_id": 109,
        "age": 23,
        "gender": "Male",
        "email": "karan.mehta@gmail.com",
        "status": "Active"
    },
    {
        "student_id": 110,
        "name": "Anjali Joshi",
        "age": 21,
        "email": "anjali.joshi@gmail.com",
        "status": "Active"
    }
]

In [8]:
df = pd.DataFrame(data)
df

   student_id            name  age  gender                     email    status
0         101     Amir Shaikh   22    Male     amir.shaikh@gmail.com    Active
1         102     Rahul Patil   21    Male     rahul.patil@gmail.com    Active
2         103    Sneha Jadhav   20  Female    sneha.jadhav@gmail.com  Inactive
3         104    Priya Sharma   22  Female    priya.sharma@gmail.com    Active
4         105      Amit Kumar   23    Male                       NaN    Active
5         106     Pooja Singh   21  Female                       NaN    Active
6         107  Rohan Deshmukh   22    Male  rohan.deshmukh@gmail.com  Inactive
7         108      Neha Verma   20  Female      neha.verma@gmail.com    Active
8         109             NaN   23    Male     karan.mehta@gmail.com    Active
9         110    Anjali Joshi   21     NaN    anjali.joshi@gmail.com    Active

In [9]:
df.isna().sum()

student_id    0
name          1
age           0
gender        1
email         2
status        0
dtype: int64

In [10]:
df.dtypes

student_id     int64
name          object
age            int64
gender        object
email         object
status        object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  10 non-null     int64
 1   name        9 non-null      object
 2   age         10 non-null     int64
 3   gender      9 non-null      object
 4   email       8 non-null      object
 5   status      10 non-null     object
dtypes: int64(2), object(4)
memory usage: 612.0+ bytes

In [19]:
df.fillna("__")

   student_id            name  age  gender                     email    status
0         101     Amir Shaikh   22    Male     amir.shaikh@gmail.com    Active
1         102     Rahul Patil   21    Male     rahul.patil@gmail.com    Active
2         103    Sneha Jadhav   20  Female    sneha.jadhav@gmail.com  Inactive
3         104    Priya Sharma   22  Female    priya.sharma@gmail.com    Active
4         105      Amit Kumar   23    Male                        __    Active
5         106     Pooja Singh   21  Female                        __    Active
6         107  Rohan Deshmukh   22    Male  rohan.deshmukh@gmail.com  Inactive
7         108      Neha Verma   20  Female      neha.verma@gmail.com    Active
8         109              __   23    Male     karan.mehta@gmail.com    Active
9         110    Anjali Joshi   21      __    anjali.joshi@gmail.com    Active